# -*- coding: utf-8 -*-
"""Expenditure_Copy of Main_LLM_SCM_DAG_With_Hard_Constraints_General_LLM_With_Cachexia_With_Real_Contexts_and_Units.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AEMLGeKWrmMcvm76Gz7J9ZksUyzTeeWT

Last update - 2nd Dec

**Previous notebook:**https://colab.research.google.com/drive/1ODuoqmha-s31cZqzetfLk9RuGOf-6wUJ#scrollTo=IaVXSQ6RgyDx

Things added:
- Hard constraints for each variable
- Varidator mechanism
- Iterative feedback (very simple early version)
- Structured Output via Instructor package
- Visualizaton of DAG along with GT effects and L2 norm differences
- Easy DAG data specification and run config

**Wish list:**
- Change LLM to local GPT model
- Not now, but batch prompt for the next generation
"""


# from IPython.display import Image, display # Import Image and display
from custom_display_utility import display
from validator_utlity import symbolic_range_validator
from dag_module import DAG
from dag_traversal_utility import GeneralDAGData
from prompt_generator import PromptPerNode

# from google.colab import userdata
# from google.colab import drive # Drive is not used in this context
# os.environ["GEMINI_API_KEY"] = userdata.get("GOOGLE_API_KEY")
from dag_traversal_utility import compile_dag_metadata
from llm_integration import run_llm_elicitation
from llm_response_parser import split_equations_to_terms, convert_terms_to_coeffient_df
import datetime
from visualization_utility import visualize_full_dag_effects

"""### Main Loop

#### Main DAG Parameterization
"""


def parameterize_dag(
    education_wage_data: GeneralDAGData, include_hard_constraints: bool
) -> dict:
    all_llm_responses_dfs = []  # This will store the *final* LLM response for each scenario (after validation passes)
    all_coefficients_dfs = []  # This will store the *final* coefficients for each scenario (after validation passes)
    all_scenario_validation_success = []  # New list to store validation success status for each scenario

    # Experimental id
    exp_id: str = datetime.datetime.now().strftime('%Y%m%d%H%M%S')

    education_wage_dag = DAG(
        education_wage_data.all_nodes,
        education_wage_data.raw_edges,
        education_wage_data.node_descriptions,
        education_wage_data.node_lower_bound,
        education_wage_data.node_upper_bound,
    )
    education_wage_dag.visualize_dag(
        filename="education_wage_dag", format="png", display_in_notebook=True
    )
    # Traverses raw edge format DAG and provides a list so that we can call the LLM calling later.
    dag_relationships = education_wage_dag.traverse_nodes()
    print("\n--- DAG Parent-Child Relationships ---")
    scenarios = compile_dag_metadata(
        education_wage_data, dag_relationships, include_hard_constraints
    )

    MAX_RETRIES = (
        5  # Set the maximum number of retries for LLM elicitation per scenario
    )

    for scenario_idx, scenario_to_process in enumerate(scenarios):
        print(f"\n{'=' * 80}")
        print(
            f"[SCENARIO {scenario_idx}] Starting processing for target variable: {scenario_to_process['target_variable_name']}"
        )
        print(f"{'=' * 80}\n")

        current_feedback_message = None  # Initialize feedback for the current scenario

        iteration_count = 0
        scenario_iteration_history = []  # New list to store history for *this* scenario's iterations

        # Variables to store the *last successfully validated* results for visualization outside the loop
        last_validated_coefficients_df = None
        last_validated_llm_responses_df = None
        current_scenario_succeeded = (
            False  # Flag to track if this scenario ultimately succeeded validation
        )

        while iteration_count < MAX_RETRIES:
            iteration_count += 1
            print(
                f"\n[SCENARIO {scenario_idx}, ITERATION {iteration_count}] Eliciting LLM response..."
            )

            prompt_generator = PromptPerNode(
                primary_domain_name=scenario_to_process["primary_domain_name"],
                secondary_domain_name=scenario_to_process["secondary_domain_name"],
                target_variable_name=scenario_to_process["target_variable_name"],
                direct_parent_variables=scenario_to_process["direct_parent_variables"],
                node_descriptions=scenario_to_process[
                    "node_descriptions"
                ],  # Include node descriptions here
                node_lower_bounds=scenario_to_process["node_lower_bounds"],
                node_upper_bounds=scenario_to_process["node_upper_bounds"],
                include_constraints_in_prompt=INCLUDE_HARD_CONSTRAINTS,
                feedback_message=current_feedback_message,  # Pass feedback message to the prompt generator
                phenomenon_overview=education_wage_data.phenomenon_overview,  # Pass phenomenon_overview
            )
            # --- LLM Loop ---
            elicitation_prompt = prompt_generator.get_full_prompt()
            llm_responses_df = run_llm_elicitation(
                num_responses_per_prompt=1,
                wait_sec_per_chat=2,
                elicitation_prompt=elicitation_prompt,
                debug_print=True,
            )
            llm_responses_df["scenario_idx"] = scenario_idx
            display(llm_responses_df, "llm_resp_df", exp_id=exp_id)


            # timestamp = datetime.now().strftime("%Y%m%d_%H%M")
            # llm_responses_df.to_csv(f'llm_responses_{scenario_idx}_{timestamp}.csv', index=False) # Keep this for saving individual responses for debugging if needed

            print(
                f"[SCENARIO {scenario_idx}, ITERATION {iteration_count}] --- Splitting equation terms ---"
            )
            split_terms = split_equations_to_terms(
                llm_responses_df,
                scenario_to_process["target_variable_name"],
                verbose=True,
            )

            print(
                f"[SCENARIO {scenario_idx}, ITERATION {iteration_count}] --- Converting terms to coefficients DataFrame ---"
            )
            coefficients_df = convert_terms_to_coeffient_df(
                split_terms,
                scenario_to_process["direct_parent_variables"],
                verbose=True,
                exp_id=exp_id,
            )

            validation_result = None  # Initialize to None

            if not coefficients_df.empty:
                proposed_equation_str = llm_responses_df.iloc[0]["proposed_lin_str_eq"]
                validation_result = symbolic_range_validator(
                    coefficients_df,
                    scenario_to_process["direct_parent_variables"],
                    scenario_to_process["target_variable_name"],
                    scenario_to_process["node_lower_bounds"],
                    scenario_to_process["node_upper_bounds"],
                    proposed_equation=proposed_equation_str,  # Pass the proposed equation
                )
                print("--- Full Validation Log ---")
                print(validation_result["validation_message"])
                print("--- Validation Summary ---")
                print(validation_result["summary_message"])

                # Store iteration history
                scenario_iteration_history.append(
                    {
                        "iteration_num": iteration_count,
                        "llm_response_df": llm_responses_df.copy(),  # Store a copy to avoid modification issues
                        "coefficients_df": coefficients_df.copy(),
                        "validation_result": validation_result.copy(),  # Store a copy
                    }
                )

                if validation_result["validated"]:
                    print(
                        f"[SCENARIO {scenario_idx}, ITERATION {iteration_count}] Validation passed - moving on to next scenario"
                    )
                    all_llm_responses_dfs.append(
                        llm_responses_df
                    )  # Now append the validated response
                    all_coefficients_dfs.append(
                        coefficients_df
                    )  # Now append the validated coefficients
                    last_validated_coefficients_df = (
                        coefficients_df  # Store for outside visualization
                    )
                    last_validated_llm_responses_df = (
                        llm_responses_df  # Store for outside visualization
                    )
                    current_scenario_succeeded = True  # Mark as successful
                    break  # Exit while loop for current scenario
                else:
                    print(
                        f"[SCENARIO {scenario_idx}, ITERATION {iteration_count}] Validation failed - elicitation needs to be done again"
                    )
                    current_feedback_message = validation_result[
                        "summary_message"
                    ]  # Update feedback for next iteration
                    # Continue loop for next iteration
            else:
                print(
                    f"[SCENARIO {scenario_idx}, ITERATION {iteration_count}] Warning: Coefficients DataFrame is empty. Cannot perform validation. Retrying LLM."
                )
                summary_message_empty_coeff = "Warning: Coefficients DataFrame is empty. Cannot perform validation. Retrying LLM."
                # If coefficients_df is empty, proposed_lin_str_eq might not be directly available, or could be malformed.
                # Attempt to get it if possible, otherwise note its absence.
                proposed_equation_str = (
                    llm_responses_df.iloc[0]["proposed_lin_str_eq"]
                    if not llm_responses_df.empty
                    and "proposed_lin_str_eq" in llm_responses_df.iloc[0]
                    else "N/A (equation parsing failed)"
                )
                summary_message_empty_coeff_with_eq = f"{summary_message_empty_coeff}\nProposed Equation: {proposed_equation_str}"

                scenario_iteration_history.append(
                    {
                        "iteration_num": iteration_count,
                        "llm_response_df": llm_responses_df.copy(),
                        "coefficients_df": coefficients_df.copy(),  # Might be empty
                        "validation_result": {
                            "validation_message": summary_message_empty_coeff_with_eq,
                            "validated": False,
                            "summary_message": summary_message_empty_coeff_with_eq,
                        },
                    }
                )
                current_feedback_message = summary_message_empty_coeff_with_eq  # Update feedback for next iteration
                # Continue loop for next iteration

        # After the while loop finishes:
        # If no successful validation occurred, use the last proposal from iteration history
        if not current_scenario_succeeded and scenario_iteration_history:
            print(
                f"\n[SCENARIO {scenario_idx}] Max retries ({MAX_RETRIES}) reached without successful validation. Using the last proposal."
            )
            last_iteration_data = scenario_iteration_history[-1]
            last_validated_coefficients_df = last_iteration_data["coefficients_df"]
            last_validated_llm_responses_df = last_iteration_data["llm_response_df"]
            # Also add to the 'final' lists if not already added by successful validation
            all_llm_responses_dfs.append(last_validated_llm_responses_df)
            all_coefficients_dfs.append(last_validated_coefficients_df)
            # current_scenario_succeeded remains False
        elif not current_scenario_succeeded and not scenario_iteration_history:
            print(
                f"\n[SCENARIO {scenario_idx}] No proposals generated for this scenario after all retries."
            )

        # Record the final success status for this scenario
        all_scenario_validation_success.append(current_scenario_succeeded)

        # --- Visualization and Effect Sizes (This block will now always execute if there's any proposal) ---
        if (
            last_validated_coefficients_df is not None
            and not last_validated_coefficients_df.empty
        ):
            effect_sizes = {}
            for parent_var_name in scenario_to_process["direct_parent_variables"]:
                col_name = f"beta_{parent_var_name}"
                if col_name in last_validated_coefficients_df.columns:
                    effect_sizes[parent_var_name] = last_validated_coefficients_df.loc[
                        0, col_name
                    ]

            print(
                f"[EFFECT_SIZES {scenario_idx}] Extracted for scenario:", effect_sizes
            )
            print(
                f"\n[VISUALIZATION {scenario_idx}] --- Parent-Child Relationship with Effect Sizes ---"
            )
            display(
                prompt_generator.visualize_parent_child_relationship(
                    effect_sizes=effect_sizes
                )
            )
        else:
            print(
                f"[SCENARIO {scenario_idx}] No valid or last-resort coefficients obtained for this scenario after all retries, skipping visualization."
            )

        # Optional: print or save the iteration history for this scenario
        print(f"\n[SCENARIO {scenario_idx}] Iteration history for this scenario:")
        for entry in scenario_iteration_history:
            print(
                f"  Iteration {entry['iteration_num']}: Validated = {entry['validation_result']['validated']}, Summary = {entry['validation_result']['summary_message']}"
            )

    visualize_full_dag_effects(
        scenarios,
        all_coefficients_dfs,
        education_wage_data,
        all_scenario_validation_success,
    )
    return {
        "all_llm_responses_dfs": all_llm_responses_dfs,
        "all_coefficients_dfs": all_coefficients_dfs,
        "all_scenario_validation_success": all_scenario_validation_success,
        "scenarios": scenarios,
        "education_wage_data": education_wage_data,
    }



def main():
    """#### Main Loops for Cachexia Arbitrary Bounds

    ##### Cachexia 1 disease informed - arbitrary bounds
    """

    # Cachexia1 DAG Data
    cachexia1_exp1 = GeneralDAGData(
        all_nodes={"A", "B", "F", "GC", "GM", "V"},
        raw_edges=[
            ("A", "GC"),
            ("B", "V"),
            ("F", "GM"),
            ("GC", "B"),
            ("GC", "V"),
            ("GM", "A"),
            ("GM", "B"),
            ("GM", "V"),
        ],
        node_descriptions={
            "A": "Adipate",
            "B": "Betaine",
            "F": "Fumarate",
            "GC": "Glucose",
            "GM": "Glutamine",
            "V": "Valine",
        },
        primary_domain_name="metabolic systems",
        secondary_domain_name="biochemistry",
        node_lower_bound={"A": 0, "B": 0, "F": 0, "GC": 0, "GM": 0, "V": 0},
        node_upper_bound={"A": 100, "B": 100, "F": 100, "GC": 100, "GM": 100, "V": 100},
        ground_truth_effect_sizes={
            ("GM", "A"): 0.0674,
            ("GC", "B"): 0.0181,
            ("GM", "B"): 0.1104,
            ("A", "GC"): 13.4753,
            ("F", "GM"): 10.7348,
            ("B", "V"): 0.1104,
            ("GC", "V"): 0.0068,
            ("GM", "V"): 0.0436,
        },
        phenomenon_overview="You are going to identify internal dynamics of a phenomena, Cachexia. Cachexia is a complicated metabolic syndrome related to underlying illness and characterized by muscle mass loss with or without fat mass loss that is often associated with anorexia, an inflammatory process, insulin resistance, and increased protein turnover.",
    )

    cachexia1_exp1_results = parameterize_dag(cachexia1_exp1, include_hard_constraints=True)
