# TODO: move them into separate files later

"""##### Ablation, arbitrary hard constraints [0, 100]"""


# Expenditure DAG Data with estimated bounds and domain information
expenditure_dag_data = GeneralDAGData(
    all_nodes={
        "Card",
        "Reports",
        "Age",
        "Income",
        "Share",
        "Expenditure",
        "Owner",
        "Selfemp",
        "Dependents",
        "Months",
        "Majorcards",
        "Active",
    },
    raw_edges=[
        ("Card", "Reports"),
        ("Card", "Share"),
        ("Card", "Owner"),
        ("Card", "Majorcards"),
        ("Age", "Income"),
        ("Age", "Share"),
        ("Age", "Owner"),
        ("Age", "Months"),
        ("Income", "Expenditure"),
        ("Income", "Selfemp"),
        ("Income", "Dependents"),
        ("Income", "Majorcards"),
        ("Income", "Active"),
        ("Share", "Expenditure"),
        ("Owner", "Income"),
        ("Owner", "Dependents"),
        ("Owner", "Active"),
        ("Months", "Owner"),
        ("Majorcards", "Active"),
        ("Active", "Reports"),
    ],
    node_descriptions={
        "Card": "Whether the application for credit card was accepted or not (Categorical/Binary).",
        "Reports": "The number of major derogatory reports (Count).",
        "Age": "The age in years plus twelfths of a year (Unit: Years + fractions).",
        "Income": "The yearly income in $10,000 (Unit: 10,000 USD).",
        "Share": "The ratio of monthly credit card expenditure to yearly income (Ratio).",
        "Expenditure": "The average monthly credit card expenditure (Monetary/Continuous).",
        "Owner": "Whether the person owns their home or they rent (Categorical/Binary).",
        "Selfemp": "Whether the person is self employed or not (Categorical/Binary).",
        "Dependents": "The number of dependents + 1 (Count).",
        "Months": "The number of months living at current address (Unit: Months).",
        "Majorcards": "The number of major credit cards held (Count).",
        "Active": "The number of active credit accounts (Count).",
    },
    primary_domain_name="Finance",
    secondary_domain_name="Consumer Behavior",
    node_lower_bound={
        "Card": 0,
        "Reports": 0,
        "Age": 0,
        "Income": 0.0,
        "Share": 0.0,
        "Expenditure": 0.0,
        "Owner": 0,
        "Selfemp": 0,
        "Dependents": 0,
        "Months": 0,
        "Majorcards": 0,
        "Active": 0,
    },
    node_upper_bound={
        "Card": 100,
        "Reports": 100,
        "Age": 100,
        "Income": 100,
        "Share": 100,
        "Expenditure": 100,
        "Owner": 100,
        "Selfemp": 100,
        "Dependents": 100,
        "Months": 100,
        "Majorcards": 100,
        "Active": 100,
    },
    ground_truth_effect_sizes={
        ("Card", "Reports"): -1.52254735864156,
        ("Active", "Reports"): 0.0524304077175797,
        ("Age", "Income"): 0.0396322368121011,
        ("Owner", "Income"): 0.81007553939645,
        ("Card", "Share"): 0.0880188466837473,
        ("Age", "Share"): -0.00108166463383845,
        ("Income", "Expenditure"): 52.6677840700376,
        ("Share", "Expenditure"): 2463.53664138429,
        ("Card", "Owner"): 0.175729766661258,
        ("Age", "Owner"): 0.0159375978980603,
        ("Months", "Owner"): 0.000724193422780255,
        ("Income", "Selfemp"): 0.0168077274438035,
        ("Income", "Dependents"): 0.178844201299536,
        ("Owner", "Dependents"): 0.578697741529175,
        ("Age", "Months"): 2.85155286459752,
        ("Card", "Majorcards"): 0.0912752579655268,
        ("Income", "Majorcards"): 0.0223298793850125,
        ("Income", "Active"): 0.345808846307825,
        ("Owner", "Active"): 3.03113288530365,
        ("Majorcards", "Active"): 1.53996015363929,
    },
    phenomenon_overview="This dataset focuses on factors influencing credit card behavior and expenditure patterns, providing insights into consumer finance decisions.",
)


"""#### Other DAGs with [0, 100] constraints

https://link.springer.com/article/10.1007/s00291-020-00588-8

##### foodsecurity
"""

foodsecurity_dag_data = GeneralDAGData(
    all_nodes={"Cost", "Educational_Attainment", "Health", "Social_Cohesion"},
    raw_edges=[
        ("Educational_Attainment", "Social_Cohesion"),
        ("Health", "Cost"),
        ("Health", "Educational_Attainment"),
        ("Health", "Social_Cohesion"),
    ],
    node_descriptions={
        "Cost": "Cost of food (e.g., affordability, access).",
        "Educational_Attainment": "Level of education achieved.",
        "Health": "Overall health status of individuals.",
        "Social_Cohesion": "Strength of community ties and social support.",
    },
    primary_domain_name="Public Health",
    secondary_domain_name="Socioeconomics",
    node_lower_bound={
        "Cost": 0.0,
        "Educational_Attainment": 0.0,
        "Health": 0.0,
        "Social_Cohesion": 0.0,
    },
    node_upper_bound={
        "Cost": 100.0,
        "Educational_Attainment": 100.0,
        "Health": 100.0,
        "Social_Cohesion": 100.0,
    },
    ground_truth_effect_sizes={
        ("Health", "Cost"): 10.0,
        ("Health", "Educational_Attainment"): 7.0,
        ("Educational_Attainment", "Social_Cohesion"): 10.0,
        ("Health", "Social_Cohesion"): 17.0,
    },
    phenomenon_overview=None,
)


"""##### algal2"""

algal2_dag_data = GeneralDAGData(
    all_nodes={
        "ChiA",
        "ChiA_PS",
        "Colour",
        "Colour_PS",
        "Cyanobacteria",
        "RainSum",
        "TP",
        "TP_PS",
        "WindSpeed",
    },
    raw_edges=[
        ("ChiA", "Cyanobacteria"),
        ("ChiA_PS", "ChiA"),
        ("Colour", "Cyanobacteria"),
        ("Colour_PS", "Colour"),
        ("RainSum", "Colour"),
        ("TP", "ChiA"),
        ("TP_PS", "ChiA_PS"),
        ("TP_PS", "TP"),
        ("WindSpeed", "ChiA"),
    ],
    node_descriptions={
        "ChiA": "Chlorophyll A concentration",
        "ChiA_PS": "Chlorophyll A concentration, previous sample",
        "Colour": "Water color",
        "Colour_PS": "Water color, previous sample",
        "Cyanobacteria": "Cyanobacteria count",
        "RainSum": "Sum of rainfall",
        "TP": "Total Phosphorus concentration",
        "TP_PS": "Total Phosphorus concentration, previous sample",
        "WindSpeed": "Wind speed",
    },
    primary_domain_name="Ecology",
    secondary_domain_name="Environmental Science",
    node_lower_bound={
        "ChiA": 0.0,
        "ChiA_PS": 0.0,
        "Colour": 0.0,
        "Colour_PS": 0.0,
        "Cyanobacteria": 0.0,
        "RainSum": 0.0,
        "TP": 0.0,
        "TP_PS": 0.0,
        "WindSpeed": 0.0,
    },
    node_upper_bound={
        "ChiA": 100.0,
        "ChiA_PS": 100.0,
        "Colour": 100.0,
        "Colour_PS": 100.0,
        "Cyanobacteria": 100.0,
        "RainSum": 100.0,
        "TP": 100.0,
        "TP_PS": 100.0,
        "WindSpeed": 100.0,
    },
    ground_truth_effect_sizes={
        ("ChiA_PS", "ChiA"): 0.33,
        ("TP", "ChiA"): 0.47,
        ("WindSpeed", "ChiA"): -5.1,
        ("TP_PS", "ChiA_PS"): 0.62,
        ("Colour_PS", "Colour"): 0.81,
        ("RainSum", "Colour"): 0.028,
        ("ChiA", "Cyanobacteria"): 0.17,
        ("Colour", "Cyanobacteria"): -0.024,
        ("TP_PS", "TP"): 0.61,
    },
    phenomenon_overview="This network describes relationships between various environmental factors and algal blooms in a body of water.",
)


"""##### lexical

```
=======================================================
Processing network: lexical
=======================================================

--- Class of the bnRep network (lexical) ---
[1] "bn.fit"      "bn.fit.gnet"

--- Ground Truth Effect Sizes ---
ground_truth_effect_sizes={
        ('prev_heard', 'area'): 1.279619,
        ('prev_used', 'area'): -0.5456541,
        ('aoa', 'genre_disp'): 0.1493371,
        ('log_freq', 'genre_disp'): 0.1369712,
        ('log_range', 'genre_disp'): 0.2290909,
        ('prev_heard', 'genre_disp'): 0.4137189,
        ('prev_heard', 'log_freq'): -0.2389613,
        ('prev_used', 'log_freq'): 0.6522685,
        ('log_freq', 'log_range'): 0.453501,
        ('prev_used', 'log_range'): 0.2927989,
        ('aoa', 'prev_heard'): -0.422608,
        ('prev_heard', 'prev_used'): 0.9072148,
        ('aoa', 'social_disp'): -0.1212857,
        ('area', 'social_disp'): 0.604543,
    },

--- All Nodes ---
all_nodes={"aoa", "area", "genre_disp", "log_freq", "log_range", "prev_heard", "prev_used", "social_disp"},

--- Raw Edges ---
raw_edges=[
        ("aoa", "genre_disp"),
        ("aoa", "prev_heard"),
        ("aoa", "social_disp"),
        ("area", "social_disp"),
        ("log_freq", "genre_disp"),
        ("log_freq", "log_range"),
        ("log_range", "genre_disp"),
        ("prev_heard", "area"),
        ("prev_heard", "genre_disp"),
        ("prev_heard", "log_freq"),
        ("prev_heard", "prev_used"),
        ("prev_used", "area"),
        ("prev_used", "log_freq"),
        ("prev_used", "log_range")
    ],

```
"""

lexical_dag_data = GeneralDAGData(
    all_nodes={
        "aoa",
        "area",
        "genre_disp",
        "log_freq",
        "log_range",
        "prev_heard",
        "prev_used",
        "social_disp",
    },
    raw_edges=[
        ("aoa", "genre_disp"),
        ("aoa", "prev_heard"),
        ("aoa", "social_disp"),
        ("area", "social_disp"),
        ("log_freq", "genre_disp"),
        ("log_freq", "log_range"),
        ("log_range", "genre_disp"),
        ("prev_heard", "area"),
        ("prev_heard", "genre_disp"),
        ("prev_heard", "log_freq"),
        ("prev_heard", "prev_used"),
        ("prev_used", "area"),
        ("prev_used", "log_freq"),
        ("prev_used", "log_range"),
    ],
    node_descriptions={
        "aoa": "Age of Acquisition",
        "area": "Area of usage",
        "genre_disp": "Genre Dispersion",
        "log_freq": "Log Frequency",
        "log_range": "Log Range",
        "prev_heard": "Previously Heard",
        "prev_used": "Previously Used",
        "social_disp": "Social Dispersion",
    },
    primary_domain_name="Linguistics",
    secondary_domain_name="Cognitive Science",
    node_lower_bound={
        "aoa": 0.0,
        "area": 0.0,
        "genre_disp": 0.0,
        "log_freq": 0.0,
        "log_range": 0.0,
        "prev_heard": 0.0,
        "prev_used": 0.0,
        "social_disp": 0.0,
    },
    node_upper_bound={
        "aoa": 100.0,
        "area": 100.0,
        "genre_disp": 100.0,
        "log_freq": 100.0,
        "log_range": 100.0,
        "prev_heard": 100.0,
        "prev_used": 100.0,
        "social_disp": 100.0,
    },
    ground_truth_effect_sizes={
        ("prev_heard", "area"): 1.279619,
        ("prev_used", "area"): -0.5456541,
        ("aoa", "genre_disp"): 0.1493371,
        ("log_freq", "genre_disp"): 0.1369712,
        ("log_range", "genre_disp"): 0.2290909,
        ("prev_heard", "genre_disp"): 0.4137189,
        ("prev_heard", "log_freq"): -0.2389613,
        ("prev_used", "log_freq"): 0.6522685,
        ("log_freq", "log_range"): 0.453501,
        ("prev_used", "log_range"): 0.2927989,
        ("aoa", "prev_heard"): -0.422608,
        ("prev_heard", "prev_used"): 0.9072148,
        ("aoa", "social_disp"): -0.1212857,
        ("area", "social_disp"): 0.604543,
    },
    phenomenon_overview="This network models lexical properties and their relationships.",
)


"""##### liquefaction

```
=======================================================
Processing network: liquefaction
=======================================================

--- Class of the bnRep network (liquefaction) ---
[1] "bn.fit"      "bn.fit.gnet"

--- Ground Truth Effect Sizes ---
ground_truth_effect_sizes={
        ('lnR', 'lnamax'): -0.307873843121311,
        ('Mw', 'lnamax'): 0.41908404951763,
        ('lnR', 'lnt'): -0.729126859129163,
        ('Mw', 'lnt'): 1.91326821221389,
        ('Sigmav', 'N160'): 0.00907224603603644,
        ('Ds', 'S'): -0.00832616014865797,
        ('GWT', 'S'): 0.000777814682337057,
        ('lnamax', 'S'): 0.0938939306816531,
        ('lnR', 'S'): -0.00306747566719272,
        ('lnt', 'S'): -0.010246146273104,
        ('Mw', 'S'): 0.0534088869851398,
        ('N160', 'S'): -0.00871964886165512,
        ('Ts', 'S'): 0.0164373806481002,
        ('Ds', 'Sigmav'): 8.65954393507753,
        ('GWT', 'Sigmav'): 8.63429241267473,
    },

--- All Nodes ---
all_nodes={"Ds", "GWT", "lnamax", "lnR", "lnt", "Mw", "N160", "S", "Sigmav", "Ts"},

--- Raw Edges ---
raw_edges=[
        ("Ds", "S"),
        ("Ds", "Sigmav"),
        ("GWT", "S"),
        ("GWT", "Sigmav"),
        ("lnamax", "S"),
        ("lnR", "lnamax"),
        ("lnR", "lnt"),
        ("lnR", "S"),
        ("lnt", "S"),
        ("Mw", "lnamax"),
        ("Mw", "lnt"),
        ("Mw", "S"),
        ("N160", "S"),
        ("Sigmav", "N160"),
        ("Ts", "S")
    ],

```
"""

liquefaction_dag_data = GeneralDAGData(
    all_nodes={"Ds", "GWT", "lnamax", "lnR", "lnt", "Mw", "N160", "S", "Sigmav", "Ts"},
    raw_edges=[
        ("Ds", "S"),
        ("Ds", "Sigmav"),
        ("GWT", "S"),
        ("GWT", "Sigmav"),
        ("lnamax", "S"),
        ("lnR", "lnamax"),
        ("lnR", "lnt"),
        ("lnR", "S"),
        ("lnt", "S"),
        ("Mw", "lnamax"),
        ("Mw", "lnt"),
        ("Mw", "S"),
        ("N160", "S"),
        ("Sigmav", "N160"),
        ("Ts", "S"),
    ],
    node_descriptions={
        "Ds": "Soil depth",
        "GWT": "Groundwater table depth",
        "lnamax": "Log of peak ground acceleration",
        "lnR": "Log of epicentral distance",
        "lnt": "Log of earthquake duration",
        "Mw": "Moment magnitude of earthquake",
        "N160": "Standard Penetration Test N-value (normalized)",
        "S": "Liquefaction potential index",
        "Sigmav": "Vertical effective stress",
        "Ts": "Soil type",
    },
    primary_domain_name="Geotechnical Engineering",
    secondary_domain_name="Seismology",
    node_lower_bound={
        "Ds": 0.0,
        "GWT": 0.0,
        "lnamax": 0.0,
        "lnR": 0.0,
        "lnt": 0.0,
        "Mw": 0.0,
        "N160": 0.0,
        "S": 0.0,
        "Sigmav": 0.0,
        "Ts": 0.0,
    },
    node_upper_bound={
        "Ds": 100.0,
        "GWT": 100.0,
        "lnamax": 100.0,
        "lnR": 100.0,
        "lnt": 100.0,
        "Mw": 100.0,
        "N160": 100.0,
        "S": 100.0,
        "Sigmav": 100.0,
        "Ts": 100.0,
    },
    ground_truth_effect_sizes={
        ("lnR", "lnamax"): -0.307873843121311,
        ("Mw", "lnamax"): 0.41908404951763,
        ("lnR", "lnt"): -0.729126859129163,
        ("Mw", "lnt"): 1.91326821221389,
        ("Sigmav", "N160"): 0.00907224603603644,
        ("Ds", "S"): -0.00832616014865797,
        ("GWT", "S"): 0.000777814682337057,
        ("lnamax", "S"): 0.0938939306816531,
        ("lnR", "S"): -0.00306747566719272,
        ("lnt", "S"): -0.010246146273104,
        ("Mw", "S"): 0.0534088869851398,
        ("N160", "S"): -0.00871964886165512,
        ("Ts", "S"): 0.0164373806481002,
        ("Ds", "Sigmav"): 8.65954393507753,
        ("GWT", "Sigmav"): 8.63429241267473,
    },
    phenomenon_overview="This network models factors influencing soil liquefaction potential during earthquakes.",
)

"""##### stocks"""

stocks_dag_data = GeneralDAGData(
    all_nodes={
        "AEFES",
        "AKSEN",
        "CCOLA",
        "ENJSA",
        "KERVT",
        "LKMNH",
        "MPARK",
        "ODAS",
        "PENGD",
        "TUKAS",
        "ULKER",
        "ULUUN",
        "ZOREN",
    },
    raw_edges=[
        ("AEFES", "CCOLA"),
        ("AEFES", "ENJSA"),
        ("AEFES", "MPARK"),
        ("AKSEN", "ENJSA"),
        ("AKSEN", "MPARK"),
        ("KERVT", "ENJSA"),
        ("KERVT", "PENGD"),
        ("KERVT", "TUKAS"),
        ("KERVT", "ULKER"),
        ("LKMNH", "MPARK"),
        ("LKMNH", "ULUUN"),
        ("ODAS", "AKSEN"),
        ("ODAS", "MPARK"),
        ("ODAS", "ZOREN"),
        ("PENGD", "TUKAS"),
        ("TUKAS", "ODAS"),
        ("ULKER", "CCOLA"),
        ("ULKER", "MPARK"),
        ("ULUUN", "KERVT"),
        ("ZOREN", "AEFES"),
        ("ZOREN", "AKSEN"),
        ("ZOREN", "ENJSA"),
        ("ZOREN", "ULKER"),
    ],
    node_descriptions={
        "AEFES": "Stock price of AEFES",
        "AKSEN": "Stock price of AKSEN",
        "CCOLA": "Stock price of CCOLA",
        "ENJSA": "Stock price of ENJSA",
        "KERVT": "Stock price of KERVT",
        "LKMNH": "Stock price of LKMNH",
        "MPARK": "Stock price of MPARK",
        "ODAS": "Stock price of ODAS",
        "PENGD": "Stock price of PENGD",
        "TUKAS": "Stock price of TUKAS",
        "ULKER": "Stock price of ULKER",
        "ULUUN": "Stock price of ULUUN",
        "ZOREN": "Stock price of ZOREN",
    },
    primary_domain_name="Finance",
    secondary_domain_name="Market Analysis",
    node_lower_bound={
        "AEFES": 0.0,
        "AKSEN": 0.0,
        "CCOLA": 0.0,
        "ENJSA": 0.0,
        "KERVT": 0.0,
        "LKMNH": 0.0,
        "MPARK": 0.0,
        "ODAS": 0.0,
        "PENGD": 0.0,
        "TUKAS": 0.0,
        "ULKER": 0.0,
        "ULUUN": 0.0,
        "ZOREN": 0.0,
    },
    node_upper_bound={
        "AEFES": 100.0,
        "AKSEN": 100.0,
        "CCOLA": 100.0,
        "ENJSA": 100.0,
        "KERVT": 100.0,
        "LKMNH": 100.0,
        "MPARK": 100.0,
        "ODAS": 100.0,
        "PENGD": 100.0,
        "TUKAS": 100.0,
        "ULKER": 100.0,
        "ULUUN": 100.0,
        "ZOREN": 100.0,
    },
    ground_truth_effect_sizes={
        ("ZOREN", "AEFES"): 0.28504,
        ("ODAS", "AKSEN"): 0.232151,
        ("ZOREN", "AKSEN"): 0.296668,
        ("AEFES", "CCOLA"): 0.351159,
        ("ULKER", "CCOLA"): 0.225405,
        ("AEFES", "ENJSA"): 0.148784,
        ("AKSEN", "ENJSA"): 0.134633,
        ("KERVT", "ENJSA"): 0.113066,
        ("ZOREN", "ENJSA"): 0.184162,
        ("ULUUN", "KERVT"): 0.284235,
        ("AEFES", "MPARK"): 0.205706,
        ("AKSEN", "MPARK"): 0.117322,
        ("LKMNH", "MPARK"): 0.29696,
        ("ODAS", "MPARK"): 0.0683476,
        ("ULKER", "MPARK"): 0.192566,
        ("TUKAS", "ODAS"): 0.324198,
        ("KERVT", "PENGD"): 0.680582,
        ("KERVT", "TUKAS"): 0.355931,
        ("PENGD", "TUKAS"): 0.110216,
        ("KERVT", "ULKER"): 0.206911,
        ("ZOREN", "ULKER"): 0.191251,
        ("LKMNH", "ULUUN"): 0.235237,
        ("ODAS", "ZOREN"): 0.450508,
    },
    phenomenon_overview="This network models the relationships between various stock prices.",
)



"""```

=======================================================
Processing network: stocks
=======================================================

--- Class of the bnRep network (stocks) ---
[1] "bn.fit"      "bn.fit.gnet"

--- Ground Truth Effect Sizes ---
ground_truth_effect_sizes={
        ('ZOREN', 'AEFES'): 0.28504,
        ('ODAS', 'AKSEN'): 0.232151,
        ('ZOREN', 'AKSEN'): 0.296668,
        ('AEFES', 'CCOLA'): 0.351159,
        ('ULKER', 'CCOLA'): 0.225405,
        ('AEFES', 'ENJSA'): 0.148784,
        ('AKSEN', 'ENJSA'): 0.134633,
        ('KERVT', 'ENJSA'): 0.113066,
        ('ZOREN', 'ENJSA'): 0.184162,
        ('ULUUN', 'KERVT'): 0.284235,
        ('AEFES', 'MPARK'): 0.205706,
        ('AKSEN', 'MPARK'): 0.117322,
        ('LKMNH', 'MPARK'): 0.29696,
        ('ODAS', 'MPARK'): 0.0683476,
        ('ULKER', 'MPARK'): 0.192566,
        ('TUKAS', 'ODAS'): 0.324198,
        ('KERVT', 'PENGD'): 0.680582,
        ('KERVT', 'TUKAS'): 0.355931,
        ('PENGD', 'TUKAS'): 0.110216,
        ('KERVT', 'ULKER'): 0.206911,
        ('ZOREN', 'ULKER'): 0.191251,
        ('LKMNH', 'ULUUN'): 0.235237,
        ('ODAS', 'ZOREN'): 0.450508,
    },

--- All Nodes ---
all_nodes={"AEFES", "AKSEN", "CCOLA", "ENJSA", "KERVT", "LKMNH", "MPARK", "ODAS", "PENGD", "TUKAS", "ULKER", "ULUUN", "ZOREN"},

--- Raw Edges ---
raw_edges=[
        ("AEFES", "CCOLA"),
        ("AEFES", "ENJSA"),
        ("AEFES", "MPARK"),
        ("AKSEN", "ENJSA"),
        ("AKSEN", "MPARK"),
        ("KERVT", "ENJSA"),
        ("KERVT", "PENGD"),
        ("KERVT", "TUKAS"),
        ("KERVT", "ULKER"),
        ("LKMNH", "MPARK"),
        ("LKMNH", "ULUUN"),
        ("ODAS", "AKSEN"),
        ("ODAS", "MPARK"),
        ("ODAS", "ZOREN"),
        ("PENGD", "TUKAS"),
        ("TUKAS", "ODAS"),
        ("ULKER", "CCOLA"),
        ("ULKER", "MPARK"),
        ("ULUUN", "KERVT"),
        ("ZOREN", "AEFES"),
        ("ZOREN", "AKSEN"),
        ("ZOREN", "ENJSA"),
        ("ZOREN", "ULKER")
    ],
```

#### turbine1

```
=======================================================
Processing network: turbine1
=======================================================

--- Class of the bnRep network (turbine1) ---
[1] "bn.fit"      "bn.fit.gnet"

--- Ground Truth Effect Sizes ---
ground_truth_effect_sizes={
        ('TwrBsMxt', 'PtfmRoll'): 3.207186e-05,
        ('TwrBsFxt', 'PtfmSurge'): 0.0104914489,
        ('YawBrFxp', 'PtfmSurge'): -0.0113494099,
        ('YawBrMxp', 'PtfmSurge'): -0.0006205644,
        ('TwrBsFyt', 'PtfmSway'): 0.003894343,
        ('YawBrMyp', 'PtfmSway'): -3.246104e-05,
        ('PtfmSurge', 'TTDspFA'): 1.41667e-07,
        ('TwrBsFxt', 'TTDspFA'): 9.849973e-05,
        ('YawBrFxp', 'TTDspFA'): 0.0003382452,
        ('PtfmPitch', 'TTDspPtch'): -0.004537201,
        ('TwrBsMyt', 'TTDspPtch'): 6.906587e-06,
        ('YawBrMyp', 'TTDspPtch'): 1.207271e-05,
        ('PtfmRoll', 'TTDspRoll'): -0.006269582,
        ('TwrBsMxt', 'TTDspRoll'): 7.226258e-06,
        ('YawBrMxp', 'TTDspRoll'): 1.501368e-05,
        ('TwrBsFyt', 'TTDspSS'): 0.00037893559,
        ('TwrBsFxt', 'YawBrFxp'): 0.7626502,
        ('TTDspSS', 'YawBrFyp'): 2443.0219893,
        ('TwrBsFyt', 'YawBrFyp'): -0.1350949,
        ('TwrBsMxt', 'YawBrMxp'): 0.02512427,
    },

--- All Nodes ---
all_nodes={"PtfmPitch", "PtfmRoll", "PtfmSurge", "PtfmSway", "TTDspFA", "TTDspPtch", "TTDspRoll", "TTDspSS", "TwrBsFxt", "TwrBsFyt", "TwrBsMxt", "TwrBsMyt", "YawBrFxp", "YawBrFyp", "YawBrMxp", "YawBrMyp"},

--- Raw Edges ---
raw_edges=[
        ("PtfmPitch", "TTDspPtch"),
        ("PtfmRoll", "TTDspRoll"),
        ("PtfmSurge", "TTDspFA"),
        ("TTDspSS", "YawBrFyp"),
        ("TwrBsFxt", "PtfmSurge"),
        ("TwrBsFxt", "TTDspFA"),
        ("TwrBsFxt", "YawBrFxp"),
        ("TwrBsFyt", "PtfmSway"),
        ("TwrBsFyt", "TTDspSS"),
        ("TwrBsFyt", "YawBrFyp"),
        ("TwrBsMxt", "PtfmRoll"),
        ("TwrBsMxt", "TTDspRoll"),
        ("TwrBsMxt", "YawBrMxp"),
        ("TwrBsMyt", "TTDspPtch"),
        ("YawBrFxp", "PtfmSurge"),
        ("YawBrFxp", "TTDspFA"),
        ("YawBrMxp", "PtfmSurge"),
        ("YawBrMxp", "TTDspRoll"),
        ("YawBrMyp", "PtfmSway"),
        ("YawBrMyp", "TTDspPtch")
    ],

```
"""

suffocation_dag_data = GeneralDAGData(
    all_nodes={
        "N10",
        "N11",
        "N12",
        "N13",
        "N14",
        "N16",
        "N17",
        "N18",
        "N20",
        "N22",
        "N23",
        "N24",
        "N25",
        "N26",
        "N27",
        "N28",
        "N29",
        "N30",
        "N32",
        "N33",
        "N34",
        "N35",
        "N36",
        "N37",
        "N38",
        "N39",
        "N4",
        "N40",
        "N5",
        "N8",
        "OI",
        "PersonnelSuffocation",
        "UA",
        "UP",
        "US",
    },
    raw_edges=[
        ("N10", "OI"),
        ("N11", "OI"),
        ("N12", "OI"),
        ("N13", "OI"),
        ("N14", "OI"),
        ("N16", "US"),
        ("N17", "US"),
        ("N18", "US"),
        ("N20", "UA"),
        ("N22", "UA"),
        ("N23", "UA"),
        ("N24", "UA"),
        ("N25", "UA"),
        ("N26", "UA"),
        ("N27", "UA"),
        ("N28", "UA"),
        ("N29", "UA"),
        ("N30", "UA"),
        ("N32", "UA"),
        ("N33", "UP"),
        ("N34", "US"),
        ("N35", "US"),
        ("N36", "US"),
        ("N37", "US"),
        ("N38", "US"),
        ("N39", "US"),
        ("N4", "US"),
        ("N40", "UP"),
        ("N5", "UP"),
        ("N8", "UA"),
        ("OI", "PersonnelSuffocation"),
        ("UA", "PersonnelSuffocation"),
        ("UP", "PersonnelSuffocation"),
        ("US", "PersonnelSuffocation"),
    ],
    node_descriptions={
        "N10": "Factor N10",
        "N11": "Factor N11",
        "N12": "Factor N12",
        "N13": "Factor N13",
        "N14": "Factor N14",
        "N16": "Factor N16",
        "N17": "Factor N17",
        "N18": "Factor N18",
        "N20": "Factor N20",
        "N22": "Factor N22",
        "N23": "Factor N23",
        "N24": "Factor N24",
        "N25": "Factor N25",
        "N26": "Factor N26",
        "N27": "Factor N27",
        "N28": "Factor N28",
        "N29": "Factor N29",
        "N30": "Factor N30",
        "N32": "Factor N32",
        "N33": "Factor N33",
        "N34": "Factor N34",
        "N35": "Factor N35",
        "N36": "Factor N36",
        "N37": "Factor N37",
        "N38": "Factor N38",
        "N39": "Factor N39",
        "N4": "Factor N4",
        "N40": "Factor N40",
        "N5": "Factor N5",
        "N8": "Factor N8",
        "OI": "Oxygen Index",
        "PersonnelSuffocation": "Personnel Suffocation",
        "UA": "Unsafe Acts",
        "UP": "Unsafe Procedures",
        "US": "Unsafe Systems",
    },
    primary_domain_name="Safety Engineering",
    secondary_domain_name="Risk Assessment",
    node_lower_bound={
        "N10": 0.0,
        "N11": 0.0,
        "N12": 0.0,
        "N13": 0.0,
        "N14": 0.0,
        "N16": 0.0,
        "N17": 0.0,
        "N18": 0.0,
        "N20": 0.0,
        "N22": 0.0,
        "N23": 0.0,
        "N24": 0.0,
        "N25": 0.0,
        "N26": 0.0,
        "N27": 0.0,
        "N28": 0.0,
        "N29": 0.0,
        "N30": 0.0,
        "N32": 0.0,
        "N33": 0.0,
        "N34": 0.0,
        "N35": 0.0,
        "N36": 0.0,
        "N37": 0.0,
        "N38": 0.0,
        "N39": 0.0,
        "N4": 0.0,
        "N40": 0.0,
        "N5": 0.0,
        "N8": 0.0,
        "OI": 0.0,
        "PersonnelSuffocation": 0.0,
        "UA": 0.0,
        "UP": 0.0,
        "US": 0.0,
    },
    node_upper_bound={
        "N10": 100.0,
        "N11": 100.0,
        "N12": 100.0,
        "N13": 100.0,
        "N14": 100.0,
        "N16": 100.0,
        "N17": 100.0,
        "N18": 100.0,
        "N20": 100.0,
        "N22": 100.0,
        "N23": 100.0,
        "N24": 100.0,
        "N25": 100.0,
        "N26": 100.0,
        "N27": 100.0,
        "N28": 100.0,
        "N29": 100.0,
        "N30": 100.0,
        "N32": 100.0,
        "N33": 100.0,
        "N34": 100.0,
        "N35": 100.0,
        "N36": 100.0,
        "N37": 100.0,
        "N38": 100.0,
        "N39": 100.0,
        "N4": 100.0,
        "N40": 100.0,
        "N5": 100.0,
        "N8": 100.0,
        "OI": 100.0,
        "PersonnelSuffocation": 100.0,
        "UA": 100.0,
        "UP": 100.0,
        "US": 100.0,
    },
    ground_truth_effect_sizes={
        ("N10", "OI"): 0.2026,
        ("N11", "OI"): 0.153,
        ("N12", "OI"): 0.1454,
        ("N13", "OI"): 0.403,
        ("N14", "OI"): 0.0959,
        ("OI", "PersonnelSuffocation"): 0.1383,
        ("UA", "PersonnelSuffocation"): 0.3455,
        ("UP", "PersonnelSuffocation"): 0.0935,
        ("US", "PersonnelSuffocation"): 0.4227,
        ("N20", "UA"): 0.0904,
        ("N22", "UA"): 0.0671,
        ("N23", "UA"): 0.0671,
        ("N24", "UA"): 0.0671,
        ("N25", "UA"): 0.1148,
        ("N26", "UA"): 0.0935,
        ("N27", "UA"): 0.0888,
        ("N28", "UA"): 0.0671,
        ("N29", "UA"): 0.1148,
        ("N30", "UA"): 0.0671,
        ("N32", "UA"): 0.0764,
        ("N8", "UA"): 0.0858,
        ("N33", "UP"): 0.2702,
        ("N40", "UP"): 0.5166,
        ("N5", "UP"): 0.2132,
        ("N16", "US"): 0.1299,
        ("N17", "US"): 0.1299,
        ("N18", "US"): 0.1299,
        ("N34", "US"): 0.0769,
        ("N35", "US"): 0.075,
        ("N36", "US"): 0.075,
        ("N37", "US"): 0.1162,
        ("N38", "US"): 0.075,
        ("N39", "US"): 0.075,
        ("N4", "US"): 0.1173,
    },
    phenomenon_overview="This network models factors contributing to personnel suffocation incidents.",
)



turbine1_dag_data = GeneralDAGData(
    all_nodes={
        "PtfmPitch",
        "PtfmRoll",
        "PtfmSurge",
        "PtfmSway",
        "TTDspFA",
        "TTDspPtch",
        "TTDspRoll",
        "TTDspSS",
        "TwrBsFxt",
        "TwrBsFyt",
        "TwrBsMxt",
        "TwrBsMyt",
        "YawBrFxp",
        "YawBrFyp",
        "YawBrMxp",
        "YawBrMyp",
    },
    raw_edges=[
        ("PtfmPitch", "TTDspPtch"),
        ("PtfmRoll", "TTDspRoll"),
        ("PtfmSurge", "TTDspFA"),
        ("TTDspSS", "YawBrFyp"),
        ("TwrBsFxt", "PtfmSurge"),
        ("TwrBsFxt", "TTDspFA"),
        ("TwrBsFxt", "YawBrFxp"),
        ("TwrBsFyt", "PtfmSway"),
        ("TwrBsFyt", "TTDspSS"),
        ("TwrBsFyt", "YawBrFyp"),
        ("TwrBsMxt", "PtfmRoll"),
        ("TwrBsMxt", "TTDspRoll"),
        ("TwrBsMxt", "YawBrMxp"),
        ("TwrBsMyt", "TTDspPtch"),
        ("YawBrFxp", "PtfmSurge"),
        ("YawBrFxp", "TTDspFA"),
        ("YawBrMxp", "PtfmSurge"),
        ("YawBrMxp", "TTDspRoll"),
        ("YawBrMyp", "PtfmSway"),
        ("YawBrMyp", "TTDspPtch"),
    ],
    node_descriptions={
        "PtfmPitch": "Platform Pitch",
        "PtfmRoll": "Platform Roll",
        "PtfmSurge": "Platform Surge",
        "PtfmSway": "Platform Sway",
        "TTDspFA": "Tower Top Displacement Fore-Aft",
        "TTDspPtch": "Tower Top Displacement Pitch",
        "TTDspRoll": "Tower Top Displacement Roll",
        "TTDspSS": "Tower Top Displacement Side-Side",
        "TwrBsFxt": "Tower Base Force X-axis",
        "TwrBsFyt": "Tower Base Force Y-axis",
        "TwrBsMxt": "Tower Base Moment X-axis",
        "TwrBsMyt": "Tower Base Moment Y-axis",
        "YawBrFxp": "Yaw Bearing Force X-axis",
        "YawBrFyp": "Yaw Bearing Force Y-axis",
        "YawBrMxp": "Yaw Bearing Moment X-axis",
        "YawBrMyp": "Yaw Bearing Moment Y-axis",
    },
    primary_domain_name="Mechanical Engineering",
    secondary_domain_name="Renewable Energy",
    node_lower_bound={
        "PtfmPitch": 0.0,
        "PtfmRoll": 0.0,
        "PtfmSurge": 0.0,
        "PtfmSway": 0.0,
        "TTDspFA": 0.0,
        "TTDspPtch": 0.0,
        "TTDspRoll": 0.0,
        "TTDspSS": 0.0,
        "TwrBsFxt": 0.0,
        "TwrBsFyt": 0.0,
        "TwrBsMxt": 0.0,
        "TwrBsMyt": 0.0,
        "YawBrFxp": 0.0,
        "YawBrFyp": 0.0,
        "YawBrMxp": 0.0,
        "YawBrMyp": 0.0,
    },
    node_upper_bound={
        "PtfmPitch": 100.0,
        "PtfmRoll": 100.0,
        "PtfmSurge": 100.0,
        "PtfmSway": 100.0,
        "TTDspFA": 100.0,
        "TTDspPtch": 100.0,
        "TTDspRoll": 100.0,
        "TTDspSS": 100.0,
        "TwrBsFxt": 100.0,
        "TwrBsFyt": 100.0,
        "TwrBsMxt": 100.0,
        "TwrBsMyt": 100.0,
        "YawBrFxp": 100.0,
        "YawBrFyp": 100.0,
        "YawBrMxp": 100.0,
        "YawBrMyp": 100.0,
    },
    ground_truth_effect_sizes={
        ("TwrBsMxt", "PtfmRoll"): 3.207186e-05,
        ("TwrBsFxt", "PtfmSurge"): 0.0104914489,
        ("YawBrFxp", "PtfmSurge"): -0.0113494099,
        ("YawBrMxp", "PtfmSurge"): -0.0006205644,
        ("TwrBsFyt", "PtfmSway"): 0.003894343,
        ("YawBrMyp", "PtfmSway"): -3.246104e-05,
        ("PtfmSurge", "TTDspFA"): 1.41667e-07,
        ("TwrBsFxt", "TTDspFA"): 9.849973e-05,
        ("YawBrFxp", "TTDspFA"): 0.0003382452,
        ("PtfmPitch", "TTDspPtch"): -0.004537201,
        ("TwrBsMyt", "TTDspPtch"): 6.906587e-06,
        ("YawBrMyp", "TTDspPtch"): 1.207271e-05,
        ("PtfmRoll", "TTDspRoll"): -0.006269582,
        ("TwrBsMxt", "TTDspRoll"): 7.226258e-06,
        ("YawBrMxp", "TTDspRoll"): 1.501368e-05,
        ("TwrBsFyt", "TTDspSS"): 0.00037893559,
        ("TwrBsFxt", "YawBrFxp"): 0.7626502,
        ("TTDspSS", "YawBrFyp"): 2443.0219893,
        ("TwrBsFyt", "YawBrFyp"): -0.1350949,
        ("TwrBsMxt", "YawBrMxp"): 0.02512427,
    },
    phenomenon_overview="This network models the dynamics of a wind turbine.",
)

"""#### turbine2

```
=======================================================
Processing network: turbine2
=======================================================

--- Class of the bnRep network (turbine2) ---
[1] "bn.fit"      "bn.fit.gnet"

--- Ground Truth Effect Sizes ---
ground_truth_effect_sizes={
        ('TwrBsMxt', 'PtfmRoll'): 3.207186e-05,
        ('TwrBsFxt', 'PtfmSurge'): 0.0104914489,
        ('YawBrFxp', 'PtfmSurge'): -0.0113494099,
        ('YawBrMxp', 'PtfmSurge'): -0.0006205644,
        ('TwrBsFyt', 'PtfmSway'): 0.003894343,
        ('YawBrMyp', 'PtfmSway'): -3.246104e-05,
        ('PtfmSurge', 'TTDspFA'): 1.41667e-07,
        ('TwrBsFxt', 'TTDspFA'): 9.849973e-05,
        ('YawBrFxp', 'TTDspFA'): 0.0003382452,
        ('PtfmPitch', 'TTDspPtch'): 0.008012841,
        ('TwrBsMyt', 'TTDspPtch'): 6.906587e-06,
        ('YawBrMyp', 'TTDspPtch'): 1.207271e-05,
        ('PtfmRoll', 'TTDspRoll'): -0.006269582,
        ('TwrBsMxt', 'TTDspRoll'): 7.226258e-06,
        ('YawBrMxp', 'TTDspRoll'): 1.501368e-05,
        ('TwrBsFyt', 'TTDspSS'): 0.00037893559,
        ('TwrBsFxt', 'YawBrFxp'): 0.7626502,
        ('TTDspSS', 'YawBrFyp'): 2443.0219893,
        ('TwrBsFyt', 'YawBrFyp'): -0.1350949,
        ('TwrBsMxt', 'YawBrMxp'): 0.02512427,
    },

--- All Nodes ---
all_nodes={"PtfmPitch", "PtfmRoll", "PtfmSurge", "PtfmSway", "TTDspFA", "TTDspPtch", "TTDspRoll", "TTDspSS", "TwrBsFxt", "TwrBsFyt", "TwrBsMxt", "TwrBsMyt", "YawBrFxp", "YawBrFyp", "YawBrMxp", "YawBrMyp"},

--- Raw Edges ---
raw_edges=[
        ("PtfmPitch", "TTDspPtch"),
        ("PtfmRoll", "TTDspRoll"),
        ("PtfmSurge", "TTDspFA"),
        ("TTDspSS", "YawBrFyp"),
        ("TwrBsFxt", "PtfmSurge"),
        ("TwrBsFxt", "TTDspFA"),
        ("TwrBsFxt", "YawBrFxp"),
        ("TwrBsFyt", "PtfmSway"),
        ("TwrBsFyt", "TTDspSS"),
        ("TwrBsFyt", "YawBrFyp"),
        ("TwrBsMxt", "PtfmRoll"),
        ("TwrBsMxt", "TTDspRoll"),
        ("TwrBsMxt", "YawBrMxp"),
        ("TwrBsMyt", "TTDspPtch"),
        ("YawBrFxp", "PtfmSurge"),
        ("YawBrFxp", "TTDspFA"),
        ("YawBrMxp", "PtfmSurge"),
        ("YawBrMxp", "TTDspRoll"),
        ("YawBrMyp", "PtfmSway"),
        ("YawBrMyp", "TTDspPtch")
    ],

[ ]

```
"""

turbine2_dag_data = GeneralDAGData(
    all_nodes={
        "PtfmPitch",
        "PtfmRoll",
        "PtfmSurge",
        "PtfmSway",
        "TTDspFA",
        "TTDspPtch",
        "TTDspRoll",
        "TTDspSS",
        "TwrBsFxt",
        "TwrBsFyt",
        "TwrBsMxt",
        "TwrBsMyt",
        "YawBrFxp",
        "YawBrFyp",
        "YawBrMxp",
        "YawBrMyp",
    },
    raw_edges=[
        ("PtfmPitch", "TTDspPtch"),
        ("PtfmRoll", "TTDspRoll"),
        ("PtfmSurge", "TTDspFA"),
        ("TTDspSS", "YawBrFyp"),
        ("TwrBsFxt", "PtfmSurge"),
        ("TwrBsFxt", "TTDspFA"),
        ("TwrBsFxt", "YawBrFxp"),
        ("TwrBsFyt", "PtfmSway"),
        ("TwrBsFyt", "TTDspSS"),
        ("TwrBsFyt", "YawBrFyp"),
        ("TwrBsMxt", "PtfmRoll"),
        ("TwrBsMxt", "TTDspRoll"),
        ("TwrBsMxt", "YawBrMxp"),
        ("TwrBsMyt", "TTDspPtch"),
        ("YawBrFxp", "PtfmSurge"),
        ("YawBrFxp", "TTDspFA"),
        ("YawBrMxp", "PtfmSurge"),
        ("YawBrMxp", "TTDspRoll"),
        ("YawBrMyp", "PtfmSway"),
        ("YawBrMyp", "TTDspPtch"),
    ],
    node_descriptions={
        "PtfmPitch": "Platform Pitch",
        "PtfmRoll": "Platform Roll",
        "PtfmSurge": "Platform Surge",
        "PtfmSway": "Platform Sway",
        "TTDspFA": "Tower Top Displacement Fore-Aft",
        "TTDspPtch": "Tower Top Displacement Pitch",
        "TTDspRoll": "Tower Top Displacement Roll",
        "TTDspSS": "Tower Top Displacement Side-Side",
        "TwrBsFxt": "Tower Base Force X-axis",
        "TwrBsFyt": "Tower Base Force Y-axis",
        "TwrBsMxt": "Tower Base Moment X-axis",
        "TwrBsMyt": "Tower Base Moment Y-axis",
        "YawBrFxp": "Yaw Bearing Force X-axis",
        "YawBrFyp": "Yaw Bearing Force Y-axis",
        "YawBrMxp": "Yaw Bearing Moment X-axis",
        "YawBrMyp": "Yaw Bearing Moment Y-axis",
    },
    primary_domain_name="Mechanical Engineering",
    secondary_domain_name="Renewable Energy",
    node_lower_bound={
        "PtfmPitch": 0.0,
        "PtfmRoll": 0.0,
        "PtfmSurge": 0.0,
        "PtfmSway": 0.0,
        "TTDspFA": 0.0,
        "TTDspPtch": 0.0,
        "TTDspRoll": 0.0,
        "TTDspSS": 0.0,
        "TwrBsFxt": 0.0,
        "TwrBsFyt": 0.0,
        "TwrBsMxt": 0.0,
        "TwrBsMyt": 0.0,
        "YawBrFxp": 0.0,
        "YawBrFyp": 0.0,
        "YawBrMxp": 0.0,
        "YawBrMyp": 0.0,
    },
    node_upper_bound={
        "PtfmPitch": 100.0,
        "PtfmRoll": 100.0,
        "PtfmSurge": 100.0,
        "PtfmSway": 100.0,
        "TTDspFA": 100.0,
        "TTDspPtch": 100.0,
        "TTDspRoll": 100.0,
        "TTDspSS": 100.0,
        "TwrBsFxt": 100.0,
        "TwrBsFyt": 100.0,
        "TwrBsMxt": 100.0,
        "TwrBsMyt": 100.0,
        "YawBrFxp": 100.0,
        "YawBrFyp": 100.0,
        "YawBrMxp": 100.0,
        "YawBrMyp": 100.0,
    },
    ground_truth_effect_sizes={
        ("TwrBsMxt", "PtfmRoll"): 3.207186e-05,
        ("TwrBsFxt", "PtfmSurge"): 0.0104914489,
        ("YawBrFxp", "PtfmSurge"): -0.0113494099,
        ("YawBrMxp", "PtfmSurge"): -0.0006205644,
        ("TwrBsFyt", "PtfmSway"): 0.003894343,
        ("YawBrMyp", "PtfmSway"): -3.246104e-05,
        ("PtfmSurge", "TTDspFA"): 1.41667e-07,
        ("TwrBsFxt", "TTDspFA"): 9.849973e-05,
        ("YawBrFxp", "TTDspFA"): 0.0003382452,
        ("PtfmPitch", "TTDspPtch"): 0.008012841,
        ("TwrBsMyt", "TTDspPtch"): 6.906587e-06,
        ("YawBrMyp", "TTDspPtch"): 1.207271e-05,
        ("PtfmRoll", "TTDspRoll"): -0.006269582,
        ("TwrBsMxt", "TTDspRoll"): 7.226258e-06,
        ("YawBrMxp", "TTDspRoll"): 1.501368e-05,
        ("TwrBsFyt", "TTDspSS"): 0.00037893559,
        ("TwrBsFxt", "YawBrFxp"): 0.7626502,
        ("TTDspSS", "YawBrFyp"): 2443.0219893,
        ("TwrBsFyt", "YawBrFyp"): -0.1350949,
        ("TwrBsMxt", "YawBrMxp"): 0.02512427,
    },
    phenomenon_overview="This network models the dynamics of a wind turbine.",
)



"""#### expenditure_dag_data_distracted
"""
expenditure_dag_data_distracted = GeneralDAGData(
    all_nodes={
        "Card",
        "Reports",
        "Age",
        "Income",
        "Share",
        "Expenditure",
        "Owner",
        "Selfemp",
        "Dependents",
        "Months",
        "Majorcards",
        "Active",
    },
    raw_edges=[
        ("Card", "Reports"),
        ("Card", "Share"),
        ("Card", "Owner"),
        ("Card", "Majorcards"),
        ("Age", "Income"),
        ("Age", "Share"),
        ("Age", "Owner"),
        ("Age", "Months"),
        ("Income", "Expenditure"),
        ("Income", "Selfemp"),
        ("Income", "Dependents"),
        ("Income", "Majorcards"),
        ("Income", "Active"),
        ("Share", "Expenditure"),
        ("Owner", "Income"),
        ("Owner", "Dependents"),
        ("Owner", "Active"),
        ("Months", "Owner"),
        ("Majorcards", "Active"),
        ("Active", "Reports"),
        # --- NEW EDGES ADDED ---
        ("Age", "Card"),
        ("Months", "Card"),
        ("Expenditure", "Majorcards"),
        ("Dependents", "Reports"),
        ("Owner", "Share"),
    ],
    node_descriptions={
        "Card": "Whether the application for credit card was accepted or not (Categorical/Binary).",
        "Reports": "The number of major derogatory reports (Count).",
        "Age": "The age in years plus twelfths of a year (Unit: Years + fractions).",
        "Income": "The yearly income in $10,000 (Unit: 10,000 USD).",
        "Share": "The ratio of monthly credit card expenditure to yearly income (Ratio).",
        "Expenditure": "The average monthly credit card expenditure (Monetary/Continuous).",
        "Owner": "Whether the person owns their home or they rent (Categorical/Binary).",
        "Selfemp": "Whether the person is self employed or not (Categorical/Binary).",
        "Dependents": "The number of dependents + 1 (Count).",
        "Months": "The number of months living at current address (Unit: Months).",
        "Majorcards": "The number of major credit cards held (Count).",
        "Active": "The number of active credit accounts (Count).",
    },
    primary_domain_name="Finance",
    secondary_domain_name="Consumer Behavior",
    node_lower_bound={
        "Card": 0,
        "Reports": 0,
        "Age": 18,
        "Income": 0.0,
        "Share": 0.0,
        "Expenditure": 0.0,
        "Owner": 0,
        "Selfemp": 0,
        "Dependents": 1,
        "Months": 0,
        "Majorcards": 0,
        "Active": 0,
    },
    node_upper_bound={
        "Card": 1,
        "Reports": 10,
        "Age": 100,
        "Income": 500.0,
        "Share": 1.0,
        "Expenditure": 250000.0,
        "Owner": 1,
        "Selfemp": 1,
        "Dependents": 10,
        "Months": 1000,
        "Majorcards": 5,
        "Active": 10,
    },
    ground_truth_effect_sizes={
        ("Card", "Reports"): -1.52254735864156,
        ("Active", "Reports"): 0.0524304077175797,
        ("Age", "Income"): 0.0396322368121011,
        ("Owner", "Income"): 0.81007553939645,
        ("Card", "Share"): 0.0880188466837473,
        ("Age", "Share"): -0.00108166463383845,
        ("Income", "Expenditure"): 52.6677840700376,
        ("Share", "Expenditure"): 2463.53664138429,
        ("Card", "Owner"): 0.175729766661258,
        ("Age", "Owner"): 0.0159375978980603,
        ("Months", "Owner"): 0.000724193422780255,
        ("Income", "Selfemp"): 0.0168077274438035,
        ("Income", "Dependents"): 0.178844201299536,
        ("Owner", "Dependents"): 0.578697741529175,
        ("Age", "Months"): 2.85155286459752,
        ("Card", "Majorcards"): 0.0912752579655268,
        ("Income", "Majorcards"): 0.0223298793850125,
        ("Income", "Active"): 0.345808846307825,
        ("Owner", "Active"): 3.03113288530365,
        ("Majorcards", "Active"): 1.53996015363929,
        # --- NEW EFFECT SIZES (GROUND-TRUTH ZEROS) ADDED ---
        ("Age", "Card"): 0.0,
        ("Months", "Card"): 0.0,
        ("Expenditure", "Majorcards"): 0.0,
        ("Dependents", "Reports"): 0.0,
        ("Owner", "Share"): 0.0,
    },
    phenomenon_overview="This dataset focuses on factors influencing credit card behavior and expenditure patterns, providing insights into consumer finance decisions.",
)
