algal2 = {
    "name": "algal2",
    "all_nodes": {
        "ChiA",
        "ChiA_PS",
        "Colour",
        "Colour_PS",
        "Cyanobacteria",
        "RainSum",
        "TP",
        "TP_PS",
        "WindSpeed",
    },
    "raw_edges": [
        ("ChiA", "Cyanobacteria"),
        ("ChiA_PS", "ChiA"),
        ("Colour", "Cyanobacteria"),
        ("Colour_PS", "Colour"),
        ("RainSum", "Colour"),
        ("TP", "ChiA"),
        ("TP_PS", "ChiA_PS"),
        ("TP_PS", "TP"),
        ("WindSpeed", "ChiA"),
    ],
    "node_descriptions": {
        "ChiA": "Mean lake chlorophyll a concentration, current season (mg/L).",
        "ChiA_PS": "Mean lake chlorophyll a concentration, previous season (mg/L).",
        "Colour": "Mean lake colour (mg Pt/L).",
        "Colour_PS": "Mean lake colour, previous season (mg Pt/L).",
        "Cyanobacteria": "Mean lake cyanobacterial biovolume (mg/L).",
        "RainSum": "Seasonal precipitation sum (mm).",
        "TP": "Mean lake total phosphorus concentration, current season (μg/L).",
        "TP_PS": "Mean lake total phosphorus concentration, previous season (μg/L).",
        "WindSpeed": "Mean daily wind speed (m/s).",
    },
    "primary_domain_name": "Ecology",
    "secondary_domain_name": "Environmental Science",
    "node_lower_bound": {
        "ChiA": 5.0,
        "ChiA_PS": 5.0,
        "Colour": 20.0,
        "Colour_PS": 20.0,
        "Cyanobacteria": 0.0,
        "RainSum": 200.0,
        "TP": 25.0,
        "TP_PS": 25.0,
        "WindSpeed": 3.0,
    },
    "node_upper_bound": {
        "ChiA": 30.0,
        "ChiA_PS": 30.0,
        "Colour": 65.0,
        "Colour_PS": 65.0,
        "Cyanobacteria": 6.0,
        "RainSum": 550.0,
        "TP": 60.0,
        "TP_PS": 60.0,
        "WindSpeed": 5.0,
    },
    "ground_truth_effect_sizes": {
        ("ChiA_PS", "ChiA"): 0.33,
        ("TP", "ChiA"): 0.47,
        ("WindSpeed", "ChiA"): -5.1,
        ("TP_PS", "ChiA_PS"): 0.62,
        ("Colour_PS", "Colour"): 0.81,
        ("RainSum", "Colour"): 0.028,
        ("ChiA", "Cyanobacteria"): 0.17,
        ("Colour", "Cyanobacteria"): -0.024,
        ("TP_PS", "TP"): 0.61,
    },
    "phenomenon_overview": "This network describes relationships between various environmental factors and algal blooms in a body of water.",
    "include_parent_relationships": False,
}