expenditure_sp_majorcards_dependents = {
    "name": "expenditure_sp_majorcards_dependents",
    "all_nodes": {
        "Active",
        "Age",
        "Card",
        "Dependents",
        "Expenditure",
        "Income",
        "Majorcards",
        "Months",
        "Owner",
        "Reports",
        "Selfemp",
        "Share",
    },
    "raw_edges": [
        ("Card", "Reports"),
        ("Card", "Share"),
        ("Card", "Owner"),
        ("Card", "Majorcards"),
        ("Age", "Income"),
        ("Age", "Share"),
        ("Age", "Owner"),
        ("Age", "Months"),
        ("Income", "Expenditure"),
        ("Income", "Selfemp"),
        ("Income", "Dependents"),
        ("Income", "Majorcards"),
        ("Income", "Active"),
        ("Share", "Expenditure"),
        ("Owner", "Income"),
        ("Owner", "Dependents"),
        ("Owner", "Active"),
        ("Months", "Owner"),
        ("Majorcards", "Active"),
        ("Active", "Reports"),
        ("Majorcards", "Dependents"),
    ],
    "node_descriptions": {
        "Card": "Whether the application for credit card was accepted or not (Categorical/Binary).",
        "Reports": "The number of major derogatory reports (Count).",
        "Age": "The age in years plus twelfths of a year (Unit: Years + fractions).",
        "Income": "The yearly income in $10,000 (Unit: 10,000 USD).",
        "Share": "The ratio of monthly credit card expenditure to yearly income (Ratio).",
        "Expenditure": "The average monthly credit card expenditure (Monetary/Continuous).",
        "Owner": "Whether the person owns their home or they rent (Categorical/Binary).",
        "Selfemp": "Whether the person is self employed or not (Categorical/Binary).",
        "Dependents": "The number of dependents + 1 (Count).",
        "Months": "The number of months living at current address (Unit: Months).",
        "Majorcards": "The number of major credit cards held (Count).",
        "Active": "The number of active credit accounts (Count).",
    },
    "primary_domain_name": "Finance",
    "secondary_domain_name": "Consumer Behavior",
    "node_lower_bound": {
        "Card": 0,
        "Reports": 0,
        "Age": 18,
        "Income": 0.0,
        "Share": 0.0,
        "Expenditure": 0.0,
        "Owner": 0,
        "Selfemp": 0,
        "Dependents": 1,
        "Months": 0,
        "Majorcards": 0,
        "Active": 0,
    },
    "node_upper_bound": {
        "Card": 1,
        "Reports": 10,
        "Age": 100,
        "Income": 500.0,
        "Share": 1.0,
        "Expenditure": 250000.0,
        "Owner": 1,
        "Selfemp": 1,
        "Dependents": 10,
        "Months": 1000,
        "Majorcards": 5,
        "Active": 10,
    },
    "ground_truth_effect_sizes": {
        ("Card", "Reports"): -1.52254735864156,
        ("Active", "Reports"): 0.0524304077175797,
        ("Age", "Income"): 0.0396322368121011,
        ("Owner", "Income"): 0.81007553939645,
        ("Card", "Share"): 0.0880188466837473,
        ("Age", "Share"): -0.00108166463383845,
        ("Income", "Expenditure"): 52.6677840700376,
        ("Share", "Expenditure"): 2463.53664138429,
        ("Card", "Owner"): 0.175729766661258,
        ("Age", "Owner"): 0.0159375978980603,
        ("Months", "Owner"): 0.000724193422780255,
        ("Income", "Selfemp"): 0.0168077274438035,
        ("Income", "Dependents"): 0.178844201299536,
        ("Owner", "Dependents"): 0.578697741529175,
        ("Age", "Months"): 2.85155286459752,
        ("Card", "Majorcards"): 0.0912752579655268,
        ("Income", "Majorcards"): 0.0223298793850125,
        ("Income", "Active"): 0.345808846307825,
        ("Owner", "Active"): 3.03113288530365,
        ("Majorcards", "Active"): 1.53996015363929,
        ("Majorcards", "Dependents"): 0.0,
    },
    "phenomenon_overview": "This dataset focuses on factors influencing credit card behavior and expenditure patterns, providing insights into consumer finance decisions.",
}
