"""##### Cachexia 1 disease-informed - real bounds & tweaked units"""
cachexia1_disease_informed_real_bounds_tweaked_units_nm = {
    "name": "cachexia1_disease_informed_real_bounds_tweaked_units_nm",
    "all_nodes":{"A", "B", "F", "GC", "GM", "V"},
    "raw_edges":[
        ("A", "GC"),
        ("B", "V"),
        ("F", "GM"),
        ("GC", "B"),
        ("GC", "V"),
        ("GM", "A"),
        ("GM", "B"),
        ("GM", "V"),
    ],
    "node_descriptions":{
        "A": "Adipate (nanomolar, nM)",
        "B": "Betaine  (nanomolar, nM)",
        "F": "Fumarate  (nanomolar, nM)",
        "GC": "Glucose  (nanomolar, nM)",
        "GM": "Glutamine  (nanomolar, nM)",
        "V": "Valine  (nanomolar, nM)",
    },
    "primary_domain_name":"metabolic systems",
    "secondary_domain_name":"biochemistry",
    "node_lower_bound":{
        "A": 1.6 * 1000,
        "B": 2.3 * 1000,
        "F": 0.8 * 1000,
        "GC": 26.9 * 1000,
        "GM": 15.1 * 1000,
        "V": 4.1 * 1000,
    },
    "node_upper_bound":{
        "A": 325.6 * 1000,
        "B": 788.8 * 1000,
        "F": 96.6 * 1000,
        "GC": 8724.8 * 1000,
        "GM": 1684.0 * 1000,
        "V": 160.1 * 1000,
    },
    "ground_truth_effect_sizes":{
        (
            "GM",
            "A",
        ): 0.0674,  # Assuming that changing units from micro to nano does not change effect size (or regression coefficients)
        ("GC", "B"): 0.0181,
        ("GM", "B"): 0.1104,
        ("A", "GC"): 13.4753,
        ("F", "GM"): 10.7348,
        ("B", "V"): 0.1104,
        ("GC", "V"): 0.0068,
        ("GM", "V"): 0.0436,
    },
    "phenomenon_overview":"You are going to identify internal dynamics of a phenomena, Cachexia. Cachexia is a complicated metabolic syndrome related to underlying illness and characterized by muscle mass loss with or without fat mass loss that is often associated with anorexia, an inflammatory process, insulin resistance, and increased protein turnover.",
}