cachexia1_disease_blind_real_bounds_and_units = {
    "name": "cachexia1_disease_blind_real_bounds_and_units",
    "all_nodes": {"A", "B", "F", "GC", "GM", "V"},
    "raw_edges": [
        ("A", "GC"),
        ("B", "V"),
        ("F", "GM"),
        ("GC", "B"),
        ("GC", "V"),
        ("GM", "A"),
        ("GM", "B"),
        ("GM", "V"),
    ],
    "node_descriptions": {
        "A": "Adipate (micromolar, µM)",
        "B": "Betaine  (micromolar, µM)",
        "F": "Fumarate  (micromolar, µM)",
        "GC": "Glucose  (micromolar, µM)",
        "GM": "Glutamine  (micromolar, µM)",
        "V": "Valine  (micromolar, µM)",
    },
    "primary_domain_name": "metabolic systems",
    "secondary_domain_name": "biochemistry",
    "node_lower_bound": {
        "A": 1.6,
        "B": 2.3,
        "F": 0.8,
        "GC": 26.9,
        "GM": 15.1,
        "V": 4.1,
    },
    "node_upper_bound": {
        "A": 325.6,
        "B": 788.8,
        "F": 96.6,
        "GC": 8724.8,
        "GM": 1684.0,
        "V": 160.1,
    },
    "ground_truth_effect_sizes": {
        ("GM", "A"): 0.0674,
        ("GC", "B"): 0.0181,
        ("GM", "B"): 0.1104,
        ("A", "GC"): 13.4753,
        ("F", "GM"): 10.7348,
        ("B", "V"): 0.1104,
        ("GC", "V"): 0.0068,
        ("GM", "V"): 0.0436,
    },
    "phenomenon_overview": None,
    "include_parent_relationships": False,
}
